# This file is a template, and might need editing before it works on your project.
# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
image: anapsix/alpine-java:8_jdk

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

#before_script:
#  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - test
  - package
  - deploy

build-dev:
  only: 
    - dev
  stage: build
  script: ./gradlew --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - openbst/build
      - bst-java/build
      - .gradle

deploy-dev:
  only:
    - dev
  stage: deploy
  script: ./gradlew shadowJar
  artifacts:
    paths:
    - openbst/build/libs/*-full.jar
    - bst-java/build/libs
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - openbst/build
      - bst-java/build
      - .gradle
  

test-dev:
  only:
    - dev
  stage: test
  script: ./gradlew check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - openbst/build
      - bst-java/build
      - .gradle

