# Site settings
title: The BST & OpenBST Projects
subtitle: 1.0 IS OUT! SPREAD THE WORD!
email: utybodev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Create branching stories and small text-based games easily.
  Free and Open Source!
baseurl: "/BST" # the subpath of your site, e.g. /blog/
url: "http://utybo.github.io" # the base hostname & protocol for your site
# twitter_username: 
github_username:  utybo
timezone: "Europe/Paris"
# google_play: ''
# google_plus_com: ''  # Community link
# google_plus_per: '+'  #Personal link
# facebook_app_id: 12345

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: default    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]
color1: indigo
color2: amber

more_vert:
  option1:
    name: GitHub
    link: https://github.com/utybo/BST

disqus: false
# disqus_shortname: ''

# Build settings
markdown: kramdown

# Versions
versions:
- name: 1.0
  devtag: v1.0
  blogpost: /main/2016/12/26/1.0-is-coming.html
  stable: true
  jar: https://github.com/utybo/BST/releases/download/v1.0/openbst-1.0-full.jar
  tutorial: https://github.com/utybo/BST/releases/download/v1.0/The.BST.Tutorial.pdf
- name: 0.3 RC1
  devtag: v0.3-RC1
  blogpost: /main/2016/12/06/0.3-rc1-released.html
  stable: false
  jar: https://github.com/utybo/BST/releases/download/v0.3-RC1/openbst-0.3-RC1-full.jar
  tutorial: https://github.com/utybo/BST/releases/download/v0.3-RC1/The.BST.Tutorial.pdf
- name: 0.2 RC1
  devtag: v0.2-RC1
  blogpost: /main/2016/11/16/0.2-rc1-released.html
  stable: false
  jar: https://github.com/utybo/BST/releases/download/v0.2-RC1/openbst-0.2-RC1-full.jar
  tutorial: https://github.com/utybo/BST/releases/download/v0.2-RC1/The.BST.Tutorial.pdf
  examples: https://github.com/utybo/BST/releases/download/v0.2-RC1/examples.zip