# Site settings
title: "OpenBST : Interactive Fiction Tool"
email: utybodev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Create interactive fiction, branching stories and small text-based games
  easily. Free and Open Source!
baseurl: "/BST" # the subpath of your site, e.g. /blog/
url: "https://utybo.github.io" # the base hostname & protocol for your site
# twitter_username:
github_username:  utybo
timezone: "Europe/Paris"
# google_play: ''
# google_plus_com: ''  # Community link
# google_plus_per: '+'  #Personal link
# facebook_app_id: 12345
excerpt_separator: "\n"
# Layout settings
header_type: default  # values [ drawer, default ]
post_type: default    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]
color1: blue
color2: orange

more_vert:
  option1:
    name: GitHub
    link: https://github.com/utybo/BST
    accent: true
  option2:
    name: Discord Server
    link: https://discord.gg/6SVDCMM

disqus: true
# disqus_shortname: ''

defaults:
- scope :
    path: ""
    type: "posts"
  values:
    layout: "post"
    categories: "main"
    author: "utybo"
    highlight: true
    ccolor: "#000000"
